--- #YAML:1.0
name:                KiokuDB-Backend-CouchDB
version:             0.09
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent::CouchDB:             1.07
    Data::Dmap:                    0.08
    Data::Stream::Bulk:            0
    KiokuDB:                       0.24
    Moose:                         0
    Scope::Guard:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
